language: java
jdk: oraclejdk8
sudo: false
 
cache:
  directories:
    - ~/.m2
before_cache:
  - rm -rf ~/.m2/repository/org/universAAL

branches: 
 only:
 - master

env:
  global:
    secure: "R4rZ2d8ShDBWfFyBs19AbuXm4mwQRlbGlq+qw4nr0HvI+mdsRavE6W2PfY/ZAbTbU3lX6r/x1XVX3sIFI8X7vfAtmp8wfjeHLWLzfO8VRtacmCORKouNh4O8UCW76I2bmuFAuHfBY80xzyjjfnuGUyPbSaKHwzltTAtFiAAHKRk="

addons:
  apt:
    packages:
      - graphviz

before_install:
 - cd ui.pom
 - (curl -s https://raw.githubusercontent.com/universAAL/platform/master/uAAL.pom/src/scripts/settings.xml) > settings.xml
 - cp settings.xml $HOME/.m2/settings.xml
 - (curl -s https://raw.githubusercontent.com/universAAL/platform/master/uAAL.pom/src/scripts/ci.sh) > ci.sh
 - chmod +x ci.sh
 - export MY_REPO="ui"

install:
 -

before_script:
 - cat /etc/mavenrc || true
 - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc

script:
 - ./ci.sh script

after_success:
 - ./ci.sh success

notifications:
  email: false
